config/routes.rb
Rails.application.routes.draw do
  mount ShopifyApp::Engine, at: '/'
  resources :orders
  get 'create', action: :create, controller: 'orders'
  root to: 'orders#index'
  get 'export', to: 'orders#export', as: :orders_export
  get 'export_full', to: 'orders#export_full', as: :orders_export_full
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/last_order.rb
class LastOrder < ApplicationRecord
    belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
    has_one :last_order
    
    validates   :order_id, 
                :presence => {:message => "Order ID cannot be blank"},
                :uniqueness => {:message => "Order already exists"}
            
    paginates_per 25
    
    def self.to_csv(attributes = column_names, options = {})

        CSV.generate(options) do |csv|
            csv.add_row attributes

            # Iterate through all the rows.
            all.each do |foo|

                values = foo.attributes.slice(*attributes).values

                csv.add_row values
            end
        end
    end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/orders_controller.rb
class OrdersController < AuthenticatedController
  require 'csv'
  helper_method :sort_column, :sort_direction

  def index
    @orders = Order.order(sort_column + " " + sort_direction).page params[:page]
    @shop = ShopifyAPI::Shop.current.domain
  end

  def create

    # Shopify Order data
    Order.delete_all
    @orders = ShopifyAPI::Order.find(:all, params: [fulfillment_status: :unshipped, fulfillment_status: :partial, limit: 250])
    @orders = @orders.as_json

    @orders.each do |o|
      order = Order.new
      order.created_at = o["created_at"]
      order.order_id = o["id"]
      order.order_number = "1-" + o["order_number"].to_s
      order.customer = o["shipping_address"].name
      order.company = o["shipping_address"].company
      order.address1 = o["shipping_address"].address1
      order.address2 = o["shipping_address"].address2
      order.city = o["shipping_address"].city
      order.province_code = o["shipping_address"].province_code
      order.zip = o["shipping_address"].zip
      order.phone = o["shipping_address"].phone
      order.country_code = o["shipping_address"].country_code
      order.email = o["email"]
      order.order_notes = o["note"]
      order.last_order = o["customer"].last_order_id.to_s

      # Pack all skus into product_ref array
      order_skus = []
      o["line_items"].each do |item|
        if item.sku
          order_skus << item.sku
        end
      end
      order.product_ref = order_skus.join(', ')

      # Calculate the user-chosen first delivery date
      notes = []
      order.note_attributes = o["note_attributes"]
      order.note_attributes.each do |note|
        notes << note["name"] + ": " + note["value"]
        if note["name"] == 'First Delivery'
          first_delivery = note["value"]
          order.first_delivery = first_delivery
        end

        # Use preferred day as shipment ref for fulfilment team
        if note["name"] == 'Preferred Delivery Day'
          preferred_day = note["value"]
          order.shipment_ref = preferred_day
        else 
          order.shipment_ref = "Thursday"
        end
      end

      order.note_attributes = notes

      line_items = []
      order.line_items = o["line_items"]
      order.line_items.each do |item|
        if item["variant_title"] && item["variant_title"].length > 1
          title = item["variant_title"]
        else 
          title = item["title"]
        end
        if item["sku"] && item["sku"].length > 1
          title = title + " | " + item["sku"].to_s
        end
        line_items << title + ": " + item["quantity"].to_s
      end
      order.line_items = line_items

      order.tags = o["tags"]
      order.fulfillment_status = if o["fulfillment_status"].nil?
        'Unfulfilled'
      else
        o["fulfillment_status"].capitalize
      end

      order.save
    end
  end

  def export
    @data = Order.order(:created_at)
    attributes_to_include = %w(order_number customer company address1 address2 city province_code zip phone country_code email shipment_ref product_ref)
    respond_to do |format|
      format.html
      format.csv { send_data @data.to_csv(attributes_to_include), filename: "orders-#{Date.today}.csv" }
    end
  end

  def export_full
    @data = Order.order(:created_at)
    respond_to do |format|
      format.html
      format.csv { send_data @data.to_csv(), filename: "orders-#{Date.today}.csv" }
    end
  end

  private

  def sort_column 
    Order.column_names.include?(params[:sort]) ? params[:sort] : "customer"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
    def sortable(column, title=nil)
        title ||=column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>
<h2>Orders</h2>

<li><%= link_to "CSV", orders_path(format: "csv") %></li>

<ul>
  <% @orders.each do |order| %>
    <li><%= link_to order.number, "https://#{@shop_session.url}/admin/orders/#{order.id}", target: "_top" %></li>
    <%= order.customer.id %>
    <%= order.customer.first_name %>
    <%= order.customer.last_name %>
    <% order.note_attributes.each do |obj| %>
      <% obj.attributes.values.each do |attr| %>
        <%= attr %>
      <% end %>
    <% end %>
  <% end %>
</ul>

<hr>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'turbolinks:load' : 'DOMContentLoaded';

  if (!document.documentElement.hasAttribute("data-turbolinks-preview")) {
    document.addEventListener(eventName, function flash() {
      <% if flash[:notice] %>
        ShopifyApp.flashNotice(<%== flash[:notice].to_json %>);
      <% end %>

      <% if flash[:error] %>
        ShopifyApp.flashError(<%== flash[:error].to_json %>);
      <% end %>
                             
      document.removeEventListener(eventName, flash)
    });
  }
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Victory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Import Orders</h1>
<% if @orders.count == 0 %>
    No orders imported.
<% else %>
    <%= @orders.count %> orders imported.
<% end %>

<br/><br/>
<%= link_to 'View orders', orders_path, class:'button' %>

app/views/orders/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home" });
    });
  </script>
<% end %>

<h2>Orders</h2>

<div style="float:right;">
  <%= link_to "Sync Orders", create_path, class: 'button' %>
</div>

<% if @orders.empty? %>
  No orders to display
<% else %>

  <%= link_to "Export CSV (FedEx)", orders_export_path(format: "csv"), class:'button' %>
  <%= link_to "Export CSV (Full)", orders_export_full_path(format: "csv"), class:'button' %>
  <br/><br/>

  <div class="key">
    <ul>
      <li class="blue">Subscription</li>
      <li class="green">Needs Vase/Tools</li>
      <li class="sortable">Sortable</li>
    </ul>
  </div>  

  <table id="dttb">
    <thead>
      <tr>
        <th class="square">S</th>
        <th class="square">V</th>
        <th><%= sortable "order_number", "Order" %></th>
        <th><%= sortable "created_at", "Created" %></th>
        <th><%= sortable "first_delivery", "First Delivery" %></th>
        <th><%= sortable "customer" %></th>
        <th>Line Items</th>
        <th>Fulfillment Status</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |o| %>
        <tr class="parent">
          <td<% if o.tags.downcase.include? "subscription" %> data-attr-sub=true<% end %> class="square">
          </td>
          <td
            <% o.line_items.each do |value| %>
              <% if value.downcase.include? "vase" || "shears" %>
                data-attr-vase=true
              <% end %>
            <% end %>
          class="square" width="100">
          </td>
          <td>
            <%= link_to o.order_number, "https://#{@shop}/admin/orders/#{o.order_id}", target: "_blank" %>
          </td>
          <td>
            <%= o.created_at %>
          </td>
          <td>
            <%= o.first_delivery %>
          </td>
          <td>
            <%= o.customer %>
          </td>
          <td class="has-table">
            <table>
              <% o.line_items.each do |item| %>
                <tr>
                  <td>
                    <%= item %>
                  </td>
                </tr>
              <% end %>
            </table>
          </td>
          <td data-attr-fulfillment=<%= o.fulfillment_status.downcase %>>
            <%= o.fulfillment_status %>
          </td>
        </tr>
        <tr class="child" style="display:none;">
          <td class="square">&nbsp;</td>
          <td class="square">&nbsp;</td>
          <td>
            <%= o.address1 %><br/>
            <%= o.address2 %><br/>
            <%= o.city %>, <%= o.province_code %> <%= o.zip %>
          </td>
          <td><%= o.phone %></td>
          <td><%= o.email %></td>
          <td class="has-table" colspan="2">
            <table>
              <% o.note_attributes.each do |note| %>
                <tr>
                  <td><%= note %></td>
                </tr>
              <% end %>
            </table>
          </td>
          <td><%= o.order_notes %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<hr>

<%= "Displaying #{@orders.count} orders of #{@orders.total_count}" %> <br/>
<%= paginate @orders %>